### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by steventilator** [benwinding/react-admin-firebase#123]
I am encountering the following error when fetching data from certain collections in my database:

```
TypeError: Cannot read property '1' of null
    at status-code-translator.ts:31
    at DataProvider.ts:87
    at o (helpers.js:23)
    at a (helpers.js:60)
    at o (helpers.js:23)
    at a (helpers.js:60)

Warning: Missing translation for key: "Cannot read property '1' of null" 
    at Notification (http://localhost:3000/static/js/1.chunk.js:195519:31)
    at div
    at div
    at Layout (http://localhost:3000/static/js/1.chunk.js:194634:24)
    at WithStyles (http://localhost:3000/static/js/1.chunk.js:78193:31)
    at withRouter(WithStyles(Layout)) (http://localhost:3000/static/js/1.chunk.js:237053:37)
    at ConnectFunction (http://localhost:3000/static/js/1.chunk.js:234666:75)
    at ThemeProvider (http://localhost:3000/static/js/1.chunk.js:76897:24)
    at LayoutWithTheme (http://localhost:3000/static/js/1.chunk.js:194749:26)
    at Route (http://localhost:3000/static/js/1.chunk.js:236796:29)
    at Switch (http://localhost:3000/static/js/1.chunk.js:236998:29)
    at div
    at CoreAdminRouter (http://localhost:3000/static/js/1.chunk.js:163449:87)
    at Route (http://localhost:3000/static/js/1.chunk.js:236796:29)
    at Switch (http://localhost:3000/static/js/1.chunk.js:236998:29)
    at CoreAdminUI (http://localhost:3000/static/js/1.chunk.js:163650:15)
    at AdminUI
    at Router (http://localhost:3000/static/js/1.chunk.js:236431:30)
    at ConnectedRouter (http://localhost:3000/static/js/1.chunk.js:93545:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/1.chunk.js:93650:25)
    at ConnectFunction (http://localhost:3000/static/js/1.chunk.js:234666:75)
    at TranslationProvider (http://localhost:3000/static/js/1.chunk.js:169789:28)
    at Provider (http://localhost:3000/static/js/1.chunk.js:234379:20)
    at CoreAdminContext (http://localhost:3000/static/js/1.chunk.js:163218:25)
    at AdminContext
    at Admin (http://localhost:3000/static/js/1.chunk.js:201708:22)
    at App (http://localhost:3000/static/js/main.chunk.js:73:5)
```

The error occurs when fetching the resource `policies`. Everything works fine when fetching `users`. Both collections exist in my database.

```
      <Admin
        dataProvider={dataProvider}
        authProvider={authProvider}
        loginPage={CustomLoginPage}
      >
        <Resource
          name="users"
          list={UserList}
          edit={UserEdit}
          create={UserCreate}
        />
        <Resource
          name="policies"
          list={PoliciesList}
        />
      </Admin>
```

I create my providers like this:

```
const firebaseApp = firebase.initializeApp(firebaseConfig);
const options = {
  app: firebaseApp,
};
const dataProvider = FirebaseDataProvider(firebaseConfig, options);
const authProvider = FirebaseAuthProvider(firebaseConfig, options);
```

What am I doing wrong?

EDIT:

I just realized that all the collections where it doesn't work contain a field of type Reference (https://firebase.google.com/docs/firestore/manage-data/data-types). Maybe that's the problem?

**Comment by benwinding** [comment]
Hi @steventilator,

Yes, unfortunately this library is currently unable to parse the field type `ReferenceDocument`. An alternative is to use a `string` field for the document id e.g. `ref_id`. 

Cheers,
Ben

**Comment by steventilator** [comment]
I have added the ability to parse `DocumentReference`s in my branch like this: 

```
  // timestamp-parser.ts

  // Parse Firestore data type DocumentReference:
  const isDocumentReference = input.id && input.firestore && input.path;
  if (isDocumentReference) {
    return input.id;
  } 
```

https://github.com/steventilator/react-admin-firebase/blob/213e4e74236ae25a4b22bf570ca0d6e1a4b197ca/src/misc/timestamp-parser.ts#L29

It's a rather simplistic check but it seems to work. Are you interested in a pull request?

**Comment by benwinding** [comment]
Thanks for your suggestion. 

But if you save the document, the reference will be overridden with the ID string right?

We could use a prefix to identify the reference document. So the data provider can parse it correctly when reading and saving. 

An obscure prefix like this would work:

RefField=`_____ref=/path/to/refdoc`

**Comment by steventilator** [comment]
Hi @benwinding,

You are right, I never even thought about saving... 

Where would this prefix be added? Is this something I can help you with?

**Comment by steventilator** [comment]
Wow, thank you for adding this functionality so quickly, @benwinding ! I am amazed.

I have just tried the branch with the pull request, and have found one little thing that's missing: It doesn't work with the `<ReferenceField />` component yet.

I will describe the issue more precisely in the pull request thread.
