### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by semonec** [benwinding/react-admin-firebase#186]
While cloning this repository, trying to build, see this error.

**Reproduce**
```
$ git clone https://github.com/benwinding/react-admin-firebase.git
$ yarn
$ yarn start-demo

yarn run v1.22.10
$ gulp start-demo
fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/sempark/considerbeyond/react-admin-firebase/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/sempark/considerbeyond/react-admin-firebase/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/sempark/considerbeyond/react-admin-firebase/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**Environment**
* Mac OSX 11.2.1 (BigSur)
* yarn 1.22.10
* node 14.15.4

**Comment by benwinding** [comment]
Hi @semonec,

Looks like a problem in another package in node_modules.

Try  `yarn install --frozen-lockfile` as this will ensure the exact dependencies are installed.

Cheers,
Ben

**Comment by moulie415** [comment]
@benwinding your solution did not work for me however I was on node 14 and using nvm to switch to node 10 did the trick for me.
